export { GarbageScannerFormComponent } from './garbage-scanner-form.component';
export { ScannerTabsComponent } from './components/scanner-tabs/scanner-tabs.component';
export { ImageUploadComponent } from './components/image-upload/image-upload.component';
export { CameraCaptureComponent } from './components/camera-capture/camera-capture.component';
export { EcoChatComponent } from './components/eco-chat/eco-chat.component';
export { AnalysisLoadingComponent } from './components/analysis-loading/analysis-loading.component';
export { AnalyzedResultComponent } from './components/analyzed-result/analyzed-result.component';
export { ImagePreviewComponent } from './components/shared/image-preview/image-preview.component';
export { UploadAreaComponent } from './components/shared/upload-area/upload-area.component';
